#!/bin/bash
# Content generator script for ToolStack
# Called by cron to auto-generate and publish a new SEO blog post daily
set -e

SITE_DIR="/c/Users/Smelv/Projects/toolstack"
BLOG_DIR="$SITE_DIR/blog"

cd "$SITE_DIR"

# Pull latest
git pull origin master 2>/dev/null || true

# Generate timestamp
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%s)

# Write a new blog post - content will be generated by the cron agent
# The cron agent will write the HTML directly
echo "ToolStack content generator ready"
echo "Site: https://dhale1350.github.io/toolstack/"
echo "Blog: https://dhale1350.github.io/toolstack/blog/"
echo "Ready for daily content push"