import os
from datetime import datetime

# Simple generation logic for ToolStack
def generate():
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"blog/post-{date_str}.html"
    
    content = f"""
<html>
<body>
    <h1>New Content: {date_str}</h1>
    <p>This post was auto-generated by GitHub Actions.</p>
</body>
</html>
"""
    
    with open(filename, "w") as f:
        f.write(content)
    
    print(f"Generated {filename}")

if __name__ == "__main__":
    generate()
